/*
  # Image Variants Table

  ## Purpose
  Stores metadata for every optimized variant generated by the image-optimizer
  edge function. Enables the frontend to serve the best-sized image for each
  context without re-computing anything at request time.

  ## New Tables

  ### `image_variants`
  - `id` — Primary key
  - `original_url` — Full public URL of the source image (the one uploaded by admin)
  - `bucket` — Supabase Storage bucket name (e.g. "uploads")
  - `storage_path` — Path inside the bucket (e.g. "products/1234-abc.jpg")
  - `size_name` — Preset name: thumbnail | small | medium | large | original
  - `width` — Output pixel width
  - `height` — Output pixel height
  - `url` — Full public URL of this variant
  - `bytes` — File size in bytes
  - `format` — Output format: "webp" or "png"
  - `created_at` — When the variant was generated

  ## Indexes
  - `(original_url, size_name)` — Fast lookup for a specific size of a given image (unique)
  - `original_url` — Fetch all variants for one image

  ## Security
  - RLS enabled
  - Public SELECT (variants are public CDN assets)
  - Service-role only INSERT/UPDATE/DELETE (optimizer function uses service role key)
*/

CREATE TABLE IF NOT EXISTS image_variants (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  original_url  text NOT NULL,
  bucket        text NOT NULL DEFAULT 'uploads',
  storage_path  text NOT NULL,
  size_name     text NOT NULL,
  width         integer NOT NULL,
  height        integer NOT NULL,
  url           text NOT NULL,
  bytes         integer NOT NULL DEFAULT 0,
  format        text NOT NULL DEFAULT 'webp',
  created_at    timestamptz DEFAULT now()
);

-- Unique: one row per (source image × size)
CREATE UNIQUE INDEX IF NOT EXISTS image_variants_original_size_idx
  ON image_variants (original_url, size_name);

-- Fast bulk lookup by original URL
CREATE INDEX IF NOT EXISTS image_variants_original_url_idx
  ON image_variants (original_url);

ALTER TABLE image_variants ENABLE ROW LEVEL SECURITY;

-- Anyone can read variant URLs (they're public storage objects)
CREATE POLICY "Public can read image variants"
  ON image_variants FOR SELECT
  USING (true);

-- Only service role (edge functions) can write variants
CREATE POLICY "Service role can insert image variants"
  ON image_variants FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE POLICY "Service role can update image variants"
  ON image_variants FOR UPDATE
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role can delete image variants"
  ON image_variants FOR DELETE
  TO service_role
  USING (true);
